=== DImuthuUpe/create-nitro-module/src/assets/nitro-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Nitro Modules Configuration",
  "type": "object",
  "required": ["cxxNamespace", "ios", "android", "autolinking", "ignorePaths"],
  "properties": {
    "cxxNamespace": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "description": "Required: C++ namespace array"
    },
    "ios": {
      "type": "object",
      "required": ["iosModuleName"],
      "properties": {
        "iosModuleName": {
          "type": "string",
          "minLength": 1
        }
      },
      "description": "Required: iOS configuration"
    },
    "android": {
      "type": "object",
      "required": ["androidNamespace", "androidCxxLibName"],
      "properties": {
        "androidNamespace": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "androidCxxLibName": {
          "type": "string",
          "minLength": 1,
          "pattern": "/^[a-zA-Z_][a-zA-Z0-9_]*$/"
        }
      },
      "description": "Required: Android configuration"
    },
    "autolinking": {
      "type": "object",
      "description": "Required: Autolinking configuration",
      "minProperties": 1
    },
    "ignorePaths": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Required: Paths to ignore"
    }
  }
}

=== DImuthuUpe/create-nitro-module/assets/nitro-temp.json
{
  "$schema": "https://raw.githubusercontent.com/patrickkabwe/create-nitro-module/refs/heads/main/assets/nitro-schema.json",
  "cxxNamespace": ["$$cxxNamespace$$"],
  "ios": {
    "iosModuleName": "$$iosModuleName$$"
  },
  "android": {
    "androidNamespace": ["$$androidNamespace$$"],
    "androidCxxLibName": "$$androidCxxLibName$$"
  },
  "autolinking": {},
  "ignorePaths": ["node_modules"]
}
